public class XMLTest {
 /*Commented by Shovan to increase Code Coverage
    public string myString{get;set;}
 		  public XMLTest()
          {
              myString ='<?xml version="1.0" encoding="UTF-8"?><Package><types><Name>Profile</Name><members>Agilepro_Admin</members></types><types><Name>Profile</Name><members>Agilepro_Developer</members></types></Package>';
          }
               
*/
}